language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
before_install:
- export TRAVIS_COMMIT_MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- echo "$TRAVIS_COMMIT_MESSAGE"
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.2" ]]; then
    pip install coverage==3.7.1 codecov;
  else
    pip install coverage mock;
  fi;
  pip install -r requirements.txt;
script:
- 'coverage run test.py;'
after_success:
- pip install coveralls
- coveralls
before_deploy:
# create the documentation
- pip install wheel
deploy:
  provider: pypi
  user: rienafairefr
  password:
    secure: A4WVGNIpVy+1BoTV3uR34MIhntc5GCqw7qyO1qF1PiuDIrWYa/poaA5RVpPQwLb/adWYjqCiNAQsmg8PuAaPGCCxhGnGnwFZQ3j5e3lS3gdDVsSaH6trerRl8+z6uBos/BBekmnvZFoFryYEESaxMSV2p2RZKhLZqVouiqVPWwbWOoqMj7zurj2jEe1pMplHNY7bZhoEGMPpiO10ZOayrrjiKclEuP/z2MlDXakSNYhzHWAKE2ofrX/dHkA/31kjJV5MSMb4tWxt98ZGeeXa8hj9Yc3x43MBk7ohFi4/MVVGepCl5EyX6elFt3dTJbZ8nuLEY+JUALpr0OlFPG9JyNGs/6JstsKAblTLu39Bq3gsSf0KSfprt2wfNeXODQdQ7sybKP8lbnp5P63SjHmFz7S4eU+quA5Xu7a1ys72EkmncCmDvOWn4N5qugmREGksZ6m2Z2opjYDR3P1EeW8CH6Zbh3szcFmtX6YWxHrqvFYgXkIg2IREItSIlLnJxus7Z4ZcMEQMTDkv6EKVw9njUA41oZ1Fo2Az1F3Lm0a7U9ZTRmnFfaSo50l18mFfiHBS3wnjyWBM9uxc7TRqZkGwBP/qENAoPdnmv5LSkI12b23mJuaz/kx2VcnI8y5H8TwscNwI0xrovtPrt1l+kfZcmn8n/JmOQEKWzA6OFzUq/kU=
  on:
    branch: release
    distributions: sdist bdist_wheel
    repo: rienafairefr/glacier-vault-remove
    condition: $TRAVIS_PYTHON_VERSION = "2.7"